name: Update OSS Rebuild Reports

on:
  schedule:
    - cron: "50 10 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-project-reports:
    if: github.repository == 'jvm-repo-rebuild/oss-rebuild-reports'
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go toolchain
        uses: actions/setup-go@v5.5.0
        with:
          go-version: 1.22.5

      - uses: actions/checkout@v4

      - name: Update Project Reports
        run: |
          go install github.com/google/oss-rebuild/cmd/oss-rebuild@latest
          ./oss-rebuild-stats.sh

      - name: Commit Push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.email "oss-rebuild-reports@github.io"
          git config --local user.name "OSS Resbuild Reports CI"
          git add -A
          git commit -m "daily update of content"
          git push
